<?php
/** op-layout-huaxia:/html.phtml
 *
 * @created   2020-08-14
 * @version   1.0
 * @package   op-layout-huaxia

/** namespace
 *
 */
namespace OP;

/** use
 *
 */
use OP\UNIT\APP;

//	...
$layout   = Config::Get('layout')['name'] ?? null;
$hash_js  = Unit('WebPack')->Hash('js');
$hash_css = Unit('WebPack')->Hash('css');

?>
<!doctype html>
<html lang="ja">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="Content-Type"       content="text/html; charset=utf-8" />
	<meta http-equiv="Content-Style-Type" content="text/css" />
	<meta name="description" content="華夏伝統武功協会は、中国の伝統武術である螳螂拳,翻子拳,戳脚を練習・伝授しています。" />
	<meta name="keywords"    content="螳螂拳,蟷螂拳,翻子拳,戳脚,中国武術,中国拳法,カンフー" />
	<meta name="author"      content="華夏伝統武功協会公式ホームページ製作委員会" />
	<link type="text/css" href="/css/common.css" rel="stylesheet" media="screen,print" />

	<!-- Canonical -->
	<link rel="canonical" href="https://hua-xia.uqunie.com<?= $_SERVER['REQUEST_URI'] ?>" />

	<!-- Title -->
	<title><?php echo Title() ?></title>

<?php if( Env::isAdmin() ): ?>
	<!-- Stylesheet -->
	<link type="text/css" href="<?php echo "/webpack/css/?layout={$layout}&hash={$hash_css}" ?>" rel="stylesheet" />

	<!-- JavaScript -->
	<script type="text/javascript" src="<?php echo "/webpack/js/?layout={$layout}&hash={$hash_js}" ?>" defer></script>
<?php endif; ?>

</head>
	<?php \OP\Content() ?>
</html>
